---
driver:
  name: vagrant
  network:
  -
    - forwarded_port
    -
      guest: 80
      host: 8080
  -
    - private_network
    -
      ip: 192.168.33.33
  vagrantfile_erb: ".Vagrantfile.erb"
provisioner:
  name: chef_solo
  require_chef_omnibus: 12.11.18
  chef_omnibus_install_options: "-d /tmp/vagrant-cache/vagrant_omnibus"
  chef_omnibus_url: "https://omnitruck.chef.io/install.sh"
verifier:
  name: inspec
  format: documentation
platforms:
- name: centos-7.2
suites:
- name: default
  run_list:
  - recipe[chef-nextcloud::default]
  attributes:
